# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'pod725' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for pod725

  target 'pod725Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'pod725UITests' do
    inherit! :search_paths
    # Pods for testing
  end
pod 'FMDB', '~> 2.5’
pod 'MBProgressHUD', '~> 0.9.2’
pod 'UMeng', '~> 2.2.1’
pod 'SDWebImage', '~> 3.7.3’
pod 'MJRefresh', '~> 3.0.7'
pod 'JPushSDK', '~> 1.8.2’
pod 'AFNetworking', '~> 3.1.0'
pod 'MBProgressHUD', '~> 1.0.0'

end
